spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: WXqniIGKiNJgumulLrxffPlyMJeKLKKj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: sbn-production.up.railway.app
    port: 1025
    username: nour
    password: nour
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  application:
    security:
      jwt:
        secret-key: RRmWX515IUopnouresmat2018105601155026156com
        expiration: 10000000000000
      mailing:
        frontend:
          activation-url: http://localhost:4200/activate-account
      file:
        upload:
          photos-upload-path: ./uploads
    server:
      port:8080
    name: book-network
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/



